name: "Build, Test and Release"
on:
  push:
    branches:
      - main
jobs:
  classic:
    runs-on: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
      - run: nix build
